---
- name: PACKAGES | INSTALL
  yum:
    name: "{{ packages_install }}"
    state: installed
  tags:
  - smtp
  - rdp

- name: OPENVPN | EASY-RSA SOURCE DOWNLOAD
  git:
    repo: https://github.com/OpenVPN/easy-rsa.git
    dest: /usr/local/src/easy-rsa-{{ item.name }}
    update: no
  with_items: "{{ ovpn_server_instance }}"
  tags:
  - smtp
  - rdp

- name: OPENVPN | EASY-RSA VARS CHECK IF EXISTS
  stat:
    path: /usr/local/src/easy-rsa-{{ item.name }}/easyrsa3/vars
  with_items: "{{ ovpn_server_instance }}"
  register: vars_file
  tags:
  - smtp
  - rdp

- name: OPENVPN | EASY-RSA VARS COPY FROM EXAMPLE
  copy:
    src: /usr/local/src/easy-rsa-{{ item.item.name }}/easyrsa3/vars.example
    dest: /usr/local/src/easy-rsa-{{ item.item.name }}/easyrsa3/vars
    remote_src: yes
  with_items: "{{ vars_file.results }}"
  when: not item.stat.exists
  tags:
  - smtp
  - rdp

- name: OPENVPN | EASY-RSA EASYRSA_DN SET
  replace:
    path: /usr/local/src/easy-rsa-{{ item.name }}/easyrsa3/vars
    regexp: '^#(set_var\sEASYRSA_DN\s+"cn_only")'
    replace: '\1'
  with_items: "{{ ovpn_server_instance }}"
  tags:
  - smtp
  - rdp

- name: OPENVPN | EASY-RSA EASYRSA_ALGO SET
  replace:
    path: /usr/local/src/easy-rsa-{{ item.name }}/easyrsa3/vars
    regexp: '^#set_var\sEASYRSA_ALGO\s+rsa$'
    replace: 'set_var EASYRSA_ALGO            {{ item.easyrsa_algo }}'
  with_items: "{{ ovpn_server_instance }}"
  tags:
  - smtp
  - rdp

# 'secp384r1' ALLOWS CONNECTIONS FROM DOCKER CONTAINERS BASED ON ALPINE:3.8
# ALPINE:3.8 DOESN'T SUPPORT "curve = secp521r1"
- name: OPENVPN | EASY-RSA EASYRSA_CURVE SET
  replace:
    path: /usr/local/src/easy-rsa-{{ item.name }}/easyrsa3/vars
    regexp: '^#set_var\sEASYRSA_CURVE\s+secp384r1$'
    replace: 'set_var EASYRSA_CURVE           {{ item.curve }}'
  with_items: "{{ ovpn_server_instance }}"
  tags:
  - smtp
  - rdp

- name: OPENVPN | EASY-RSA EASYRSA_CA_EXPIRE SET
  replace:
    path: /usr/local/src/easy-rsa-{{ item.name }}/easyrsa3/vars
    regexp: '^#(set_var\sEASYRSA_CA_EXPIRE\s+3650)$'
    replace: '\1'
  with_items: "{{ ovpn_server_instance }}"
  tags:
  - smtp
  - rdp

- name: OPENVPN | EASY-RSA EASYRSA_CERT_EXPIRE SET
  replace:
    path: /usr/local/src/easy-rsa-{{ item.name }}/easyrsa3/vars
    regexp: '^#set_var\sEASYRSA_CERT_EXPIRE\s+1080$'
    replace: 'set_var EASYRSA_CERT_EXPIRE     3650'
  with_items: "{{ ovpn_server_instance }}"
  tags:
  - smtp
  - rdp

- name: OPENVPN | EASY-RSA EASYRSA_CRL_DAYS SET
  replace:
    path: /usr/local/src/easy-rsa-{{ item.name }}/easyrsa3/vars
    regexp: '^#set_var\sEASYRSA_CRL_DAYS\s+180$'
    replace: 'set_var EASYRSA_CRL_DAYS        3650'
  with_items: "{{ ovpn_server_instance }}"
  tags:
  - smtp
  - rdp

- name: OPENVPN | EASY-RSA CHECK IF pki DIRECTORY EXISTS
  stat:
    path: /usr/local/src/easy-rsa-{{ item.name }}/easyrsa3/pki
  with_items: "{{ ovpn_server_instance }}"
  register: pki_dir
  tags:
  - smtp
  - rdp

- name: OPENVPN | EASY-RSA init-pki
  command: ./easyrsa init-pki
  args:
    chdir: /usr/local/src/easy-rsa-{{ item.item.name }}/easyrsa3
  environment:
    EASYRSA_VARS_FILE: '/usr/local/src/easy-rsa-{{ item.item.name }}/easyrsa3/vars'
  with_items: "{{ pki_dir.results }}"
  when: not (item.stat.exists and item.stat.isdir)
  tags:
  - smtp
  - rdp

- name: OPENVPN | EASY-RSA CHECK IF ca.crt FILE EXISTS
  stat:
    path: /usr/local/src/easy-rsa-{{ item.name }}/easyrsa3/pki/ca.crt
  with_items: "{{ ovpn_server_instance }}"
  register: ca_crt_file
  tags:
  - smtp
  - rdp

- name: OPENVPN | EASY-RSA build-ca
  command: ./easyrsa --batch build-ca nopass
  args:
    chdir: /usr/local/src/easy-rsa-{{ item.item.name }}/easyrsa3
  environment:
    EASYRSA_VARS_FILE: '/usr/local/src/easy-rsa-{{ item.item.name }}/easyrsa3/vars'
  with_items: "{{ ca_crt_file.results }}"
  when: not item.stat.exists
  tags:
  - smtp
  - rdp

- name: OPENVPN | EASY-RSA CHECK IF SERVER .crt FILE EXISTS
  stat:
    path: /usr/local/src/easy-rsa-{{ item.name }}/easyrsa3/pki/issued/openvpn_server_{{ item.name }}.crt
  with_items: "{{ ovpn_server_instance }}"
  register: openvpn_server_crt_file
  tags:
  - smtp
  - rdp

- name: OPENVPN | EASY-RSA build-server-full
  command: ./easyrsa build-server-full openvpn_server_{{ item.item.name }} nopass
  args:
    chdir: /usr/local/src/easy-rsa-{{ item.item.name }}/easyrsa3
  environment:
    EASYRSA_VARS_FILE: '/usr/local/src/easy-rsa-{{ item.item.name }}/easyrsa3/vars'
  with_items: "{{ openvpn_server_crt_file.results }}"
  when: not item.stat.exists
  tags:
  - smtp
  - rdp

- name: OPENVPN | SERVER DIR CREATE
  file:
    path: /etc/openvpn/server/openvpn_server_{{ item.name }}
    state: directory
    mode: 0755
  with_items: "{{ ovpn_server_instance }}"
  tags:
  - smtp
  - rdp

- name: OPENVPN | SERVER ca.crt COPY
  copy:
    src: /usr/local/src/easy-rsa-{{ item.name }}/easyrsa3/pki/ca.crt
    dest: /etc/openvpn/server/openvpn_server_{{ item.name }}/
    remote_src: yes
  with_items: "{{ ovpn_server_instance }}"
  tags:
  - smtp
  - rdp

- name: OPENVPN | SERVER .key COPY
  copy:
    src: /usr/local/src/easy-rsa-{{ item.name }}/easyrsa3/pki/private/openvpn_server_{{ item.name }}.key
    dest: /etc/openvpn/server/openvpn_server_{{ item.name }}/
    remote_src: yes
  with_items: "{{ ovpn_server_instance }}"
  tags:
  - smtp
  - rdp

- name: OPENVPN | SERVER .crt COPY
  copy:
    src: /usr/local/src/easy-rsa-{{ item.name }}/easyrsa3/pki/issued/openvpn_server_{{ item.name }}.crt
    dest: /etc/openvpn/server/openvpn_server_{{ item.name }}/
    remote_src: yes
  with_items: "{{ ovpn_server_instance }}"
  tags:
  - smtp
  - rdp

- name: OPENVPN | SERVER HMAC KEY CHECK IF GENERATED
  stat:
    path: /etc/openvpn/server/openvpn_server_{{ item.name }}/ta.key
  with_items: "{{ ovpn_server_instance }}"
  register: ta_key_file
  tags:
  - smtp
  - rdp

- name: OPENVPN | SERVER HMAC KEY GENERATE
  command: openvpn --genkey --secret ta.key
  args:
    chdir: /etc/openvpn/server/openvpn_server_{{ item.item.name }}
  with_items: "{{ ta_key_file.results }}"
  when: not item.stat.exists
  tags:
  - smtp
  - rdp

- name: OPENVPN | SERVER Diffie-Hellman PEM COPY FROM LOCAL TO REMOTE
  copy:
    src: dh4096.pem
    dest: /etc/openvpn/server/dh4096.pem
  tags:
  - smtp
  - rdp

- name: OPENVPN | SERVER ccd DIR CREATE
  file:
    path: /etc/openvpn/server/ccd
    state: directory
    owner: root
    group: root
    mode: 0755
  tags:
  - smtp
  - rdp

# FIX ERROR:
# AUTH-PAM: BACKGROUND: user '<user>' failed to authenticate: System error
- name: OPENVPN | SERVER ENABLE PAM AUTH
  replace:
    dest: /usr/lib/systemd/system/openvpn-server@.service
    regexp: '^(CapabilityBoundingSet(?!.*\bCAP_AUDIT_WRITE\b).*)$'
    replace: '\1 CAP_AUDIT_WRITE'
  register: openvpn_service
  tags:
  - smtp
  - rdp

# FIX ERROR:
# openvpn_execve: unable to fork: Resource temporarily unavailable (errno=11)
# Exiting due to fatal error
- name: OPENVPN | SERVER ENABLE SERVICE FORK
  replace:
    path: /usr/lib/systemd/system/openvpn-server@.service
    regexp: '^(LimitNPROC=10)'
    replace: '# \1'
    backup: yes
  register: openvpn_service
  tags:
  - smtp
  - rdp

# FIX ERROR:
# Could not access file 'ccd/openvpn_client_router_01': Permission denied (errno=13)
# Could not access file 'ccd/DEFAULT': Permission denied (errno=13)
# COMMENT: ACCESS TO ccd DIR NEEDS TO ASSIGN STATIC IP-ADDRESSES TO CLIENTS
# COMMENT: PERMISSIONS MUST BE o=r+x FOR BOTH /etc/openvpn/server AND /etc/openvpn/server/ccd TO ALLOW READ FILE IN IT BY USER nobody
- name: OPENVPN | SERVER ccd DIR ENABLE ACCESS
  file:
    path: /etc/openvpn/server
    state: directory
    owner: root
    group: root
    mode: 0755
  tags:
  - smtp
  - rdp

- name: OPENVPN | FORCE SYSTEMD TO REREAD CONFIGS
  systemd:
    daemon_reload: yes
  when: openvpn_service.changed
  tags:
  - smtp
  - rdp

- name: OPENVPN | SERVER LOG DIR CREATE
  file:
    path: /var/log/openvpn
    state: directory
    mode: 0755
  tags:
  - smtp
  - rdp

- name: OPENVPN | SERVER CONFIG CREATE
  template:
    src: openvpn_server_{{ item.name }}.conf.j2
    dest: /etc/openvpn/server/openvpn_server_{{ item.name }}.conf
    owner: root
    group: root
    mode: 0644
  with_items: "{{ ovpn_server_instance }}"
  notify: OPENVPN | SERVICE RESTART
  tags:
  - smtp
  - rdp

- name: OPENVPN | SERVER SERVICE START AND ENABLE
  service:
    name: openvpn-server@openvpn_server_{{ item.name }}
    state: started
    enabled: yes
  with_items: "{{ ovpn_server_instance }}"
  tags:
  - smtp
  - rdp

- name: SYSCTL | IPv4 FORWARDING ENABLE
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_set: yes
    state: present
    reload: yes
  tags:
  - smtp
  - rdp
