---
- name: PACKAGES | INSTALL
  yum:
    name: "{{ packages_install }}"
    state: installed
  tags:
  - rdp

- name: OPENSSL | SOURCE DOWNLOAD
  unarchive:
    src: https://www.openssl.org/source/openssl-1.1.1a.tar.gz
    dest: /usr/local/src
    remote_src: yes
  tags:
  - rdp

- name: OPENSSL | CONFIGURE AND CREATE MAKEFILE | CHECK IF DONE
  stat:
    path: /usr/local/src/openssl-1.1.1a/Makefile
  register: makefile
  tags:
  - rdp

- name: OPENSSL | CONFIGURE AND CREATE MAKEFILE
  command: ./config --prefix=/usr/local/openssl --openssldir=/usr/local/openssl shared zlib
  args:
    chdir: /usr/local/src/openssl-1.1.1a
  when: not makefile.stat.exists
  tags:
  - rdp

- name: OPENSSL | MAKE | CHECK IF DONE
  stat:
    path: /usr/local/src/openssl-1.1.1a/libcrypto.so.1.1
  register: libcrypto_lib
  tags:
  - rdp

- name: OPENSSL | MAKE
  make:
    chdir: /usr/local/src/openssl-1.1.1a
  when: not libcrypto_lib.stat.exists
  tags:
  - rdp

- name: OPENSSL | MAKE INSTALL | CHECK IF DONE
  stat:
    path: /usr/local/openssl/bin/openssl
  register: openssl_bin
  tags:
  - rdp

- name: OPENSSL | MAKE INSTALL
  make:
    chdir: /usr/local/src/openssl-1.1.1a
    target: install
  when: not openssl_bin.stat.exists
  tags:
  - rdp

- name: OPENSSL | ADD NEW VERSION TO PATH
  copy:
    dest: /etc/profile.d/openssl.sh
    content: |
      pathmunge /usr/local/openssl/bin
  tags:
  - rdp

- name: OPENSSL | LINK LIBRARIES
  copy:
    dest: /etc/ld.so.conf.d/openssl-1.1.1a.conf
    content: |
      /usr/local/openssl/lib
  register: ld_so_conf
  tags:
  - rdp

- name: OPENSSL | REBUILD LIBRARIES CACHE
  command: /usr/sbin/ldconfig
  when: ld_so_conf.changed
  tags:
  - rdp

- name: STUNNEL | SOURCE DOWNLOAD
  unarchive:
    src: https://www.stunnel.org/downloads/stunnel-5.50.tar.gz
    dest: /usr/local/src
    remote_src: yes
  tags:
  - rdp

- name: STUNNEL | CONFIGURE AND CREATE MAKEFILE | CHECK IF DONE
  stat:
    path: /usr/local/src/stunnel-5.50/Makefile
  register: makefile
  tags:
  - rdp

- name: STUNNEL | CONFIGURE AND CREATE MAKEFILE
  command: ./configure
  args:
    chdir: /usr/local/src/stunnel-5.50
  when: not makefile.stat.exists
  tags:
  - rdp

- name: STUNNEL | MAKE | CHECK IF DONE
  stat:
    path: /usr/local/src/stunnel-5.50/src/stunnel
  register: stunnel_bin
  tags:
  - rdp

- name: STUNNEL | MAKE
  make:
    chdir: /usr/local/src/stunnel-5.50
  when: not stunnel_bin.stat.exists
  tags:
  - rdp

- name: STUNNEL | MAKE INSTALL | CHECK IF DONE
  stat:
    path: /usr/local/bin/stunnel
  register: stunnel_bin
  tags:
  - rdp

- name: STUNNEL | MAKE INSTALL
  make:
    chdir: /usr/local/src/stunnel-5.50
    target: install
  when: not stunnel_bin.stat.exists
  tags:
  - rdp

- name: STUNNEL | SYSTEMD SERVICE CREATE
  copy:
    dest: /usr/lib/systemd/system/stunnel.service
    content: |
      [Unit]
      Description=TLS tunnel for network daemons
      After=syslog.target network.target

      [Service]
      ExecStart=/usr/local/bin/stunnel
      Type=forking
      PrivateTmp=true

      [Install]
      WantedBy=multi-user.target
  register: stunnel_service
  tags:
  - rdp

- name: STUNNEL | FORCE SYSTEMD TO REREAD CONFIGS
  systemd:
    daemon_reload: yes
  when: stunnel_service.changed
  tags:
  - rdp

- name: STUNNEL | SERVICE USER CREATE
  user:
    name: stunnel
    home: /var/stunnel
    create_home: yes
    shell: /bin/false
    state: present
  tags:
  - rdp

- name: STUNNEL | IP-ADDRESS FIND
  setup:
    filter: ansible_default_ipv4.address
  tags:
  - rdp

- name: STUNNEL | SERVER CONFIG CREATE
  template:
    src: stunnel.conf.j2
    dest: /usr/local/etc/stunnel/stunnel.conf
    owner: root
    group: root
    mode: 0644
  tags:
  - rdp

- name: STUNNEL | PIP UPGRADE
  pip:
    name: pip
    extra_args: --upgrade
  tags:
  - rdp

- name: STUNNEL | pyOpenSSL INSTALL
  pip:
    name: pyopenssl
  tags:
  - rdp

- name: STUNNEL | DIRECTORY FOR ALL CLIENT CERTS CREATE
  file:
    path: /usr/local/etc/stunnel/cert_server
    state: directory
    mode: 0755
  tags:
  - rdp

- name: STUNNEL | OPENSSL PRIVATE KEY GENERATE
  openssl_privatekey:
    path: /usr/local/etc/stunnel/cert_server/stunnel_server.key
    type: RSA
    size: 2048
    state: present
  tags:
  - rdp

- name: STUNNEL | OPENSSL CSR GENERATE
  openssl_csr:
    path: /usr/local/etc/stunnel/cert_server/stunnel_server.csr
    privatekey_path: /usr/local/etc/stunnel/cert_server/stunnel_server.key
    common_name: www2.stunnel.ru
    state: present
  tags:
  - rdp

- name: STUNNEL | SELF SIGNED OPENSSL CERTIFICATE GENERATE
  openssl_certificate:
    path: /usr/local/etc/stunnel/cert_server/stunnel_server.crt
    privatekey_path: /usr/local/etc/stunnel/cert_server/stunnel_server.key
    csr_path: /usr/local/etc/stunnel/cert_server/stunnel_server.csr
    provider: selfsigned
    state: present
  tags:
  - rdp
